# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('tarjeta_credito', models.CharField(max_length=200)),
                ('artista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenido.Artista')),
            ],
        ),
    ]
