# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_auto_20161009_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='contenido.Artista'),
        ),
    ]
