# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 04:57
from __future__ import unicode_literals

from django.db import migrations, models


def load_stores_from_sql():
    import os
    sql_statements = open(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'sql/borrar_modelo_audio.sql'),  encoding="utf8").read()
    print(sql_statements)
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_audio_likes'),
    ]

    operations = [
        # migrations.RunSQL(load_stores_from_sql()),

        migrations.RemoveField(
            model_name='Artista_album',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='Artista_album',
            name='album',
        ),

        migrations.RemoveField(
            model_name='Album_audio',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='Album_audio',
            name='album',
        ),

        migrations.RemoveField(
            model_name='Audio',
            name='artista',
        ),

        migrations.DeleteModel("Album_audio"),
        migrations.DeleteModel("Artista_album"),

        migrations.AddField(
            model_name='Audio',
            name='artistas',
            field=models.ManyToManyField(related_name='artistas', to='contenido.Artista'),
        ),

        migrations.AddField(
            model_name='Album',
            name='artista',
            field=models.ForeignKey(related_name='artista', to='contenido.Artista')
        ),

        migrations.AddField(
            model_name='Audio',
            name='albums',
            field=models.ManyToManyField(related_name='albums', to='contenido.Album'),
        ),

    ]
