# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_album_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.Artista'),
        ),
    ]
