# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_artista_val_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fec_creacion_album',
            field=models.DateField(help_text='Fecha de creación del album'),
        ),
    ]
