# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenido', '0009_auto_20161024_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_comentario', models.TextField()),
                ('fec_creacion_comen', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del comentario')),
                ('ind_publicado', models.BooleanField(default=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.Audio')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('val_comentario',),
            },
        ),
    ]
