# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_auto_20161024_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='tags_audio',
            field=models.CharField(blank=True, help_text='Etiquetas del audio', max_length=1000, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='audio',
            name='type_audio',
            field=models.CharField(blank=True, help_text='Tipo del audio', max_length=1000, verbose_name='Audio'),
        ),
    ]
