# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_auto_20161025_1856'),
        ('contenido', '0012_artista_seguidores'),
    ]

    operations = [
    ]
