# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_merge_20161101_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
