# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_artista_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='nom_ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nom_pais',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
