# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
