# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0018_auto_20161111_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='donaciones',
            name='fec_donacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de donación'),
            preserve_default=False,
        ),
    ]
