# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0020_donaciones_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaciones',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
