# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenido', '0021_auto_20161119_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_denuncia', models.TextField(help_text='denuncia', max_length=1000)),
                ('ind_tipo_denuncia', models.CharField(help_text='Tipo de denuncia', max_length=1000, verbose_name='Tipo denuncia')),
                ('fec_creacion_denuncia', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la denuncia')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.Audio')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('val_denuncia',),
            },
        ),
    ]
